### PR TITLE
fix the expcalculator 2000 limit 

### PR DESCRIPTION
**Pull request by divinity76**
this seem to work fine up to at least lvl 500,000

seems to break somewhere between lvl 500,000 and 1 million (im not sure exactly where it breaks, but i can't be arsed checking either. pretty sure nobody will reach lvl 500k in our lifetime.)

### CODE REVIEW

**Comment by kosaa** [comment]
returned value should be rounded
```
experience_for_level(5)
> 800.0000000000002

experience_for_level(11)
> 12999.999999999998
```

**Comment by divinity76** [comment]
hmm how do you round in javascript? Number(experience_for_level(11).toFixed(0));  seems to work, but probably not the best way (convert to string and back to number sounds like a shitty hack :p )

**Comment by divinity76** [comment]
ohh Math.round() ofc

**Comment by divinity76** [comment]
@kosaa interesting! remind me, in tibia, do you start at lvl 1 or lvl 0? also i guess those 2 can just be special-cased like
```
function experience_for_level(level) {
if(level===0 || level === 1){return 0;}
  return ((50 * Math.pow(level, 3)) / 3) - (100 * Math.pow(level, 2)) + (((850 * level) / 3) - 200);
}
```
also without this special case, 1 actually returns `-0.0000000000000142108547152020037174224853515625`  (very little off, but its still wrong ^^ )

**Comment by kosaa** [comment]
> @kosaa like this? [73ba11a](https://github.com/PawelKusnierek/TibiaPal/commit/73ba11ad162abe7e197b99bebd43868c7afa8ff0)

generally yes, but to be clear comment is a candidate to delete because shortcuts like `idk` says nothing for someone who will read it

answering for your question from comment - this value looks badly because in decimal format doesnt exists exact value who represent 1 divided by 3, you will end with 0,33333(3).
Binary code doesnt have exact function value representation and you get X.00000000001 or X.999999(9)

**Comment by divinity76** [comment]
@kosaa i specialcased level 1 and replaced `idk` with `i'm not sure`

but i don't think throwing an error for lvl <1 is a good idea, because then users of experience_for_level() may need try{}catch() logic to actually handle the error.. not worth it imo?

**Pull request merged**
