### PR TITLE
Boss timer utility

### PR DESCRIPTION
**Pull request by assisjeferson**
Page to control boss timer using cookie

### CODE REVIEW

**Comment by PawelKusnierek** [comment]
Hey, I have made some changes and merged to main. Please let me know if you have any major concerns and we can discuss.

I have one question - where did you get the 'gifs' of the monsters? I would like to add a couple more, e.g. Ferumbras Mortal Shell :)

Changes I made:
1. I really like 'Boss Timers', I think it's going to be a very used feature so I moved it higher in the navigation bar, right below 'TibiaLootSplit'
2. Integrated the css changes into SASS framework
3. Changed 'cloak' word to 'timer', makes more sense in English
4. I changes the layout of the bosses quite a lot. In reality, from UX (user experience) perspective, 95% of users will only care about the 'usual' boss rotations, such as golds, graves, oberon, scarlett, mini vengoth etc. - they will not care about each individual boss e.g. realityquake, the fear fester, lord azaram etc.... so I created a new section near the top called 'Common Rotation Bosses' - and this is where I put more general timers for the whole lot of bosses that people usually do rotations for. I think this will be a lot easier for vast majority of users.
5. Added appropriate title + description to bosstimers.html
6. Added 'NEW!' by the Boss Timers in the navigation bar to draw attention to it
7. Removed css 'text shadow' from .boss-timer
8. Increased font-size for .boss-name to 16px
9. Lowered the font-size for .boss-timer to 18px
10. Switched the order of image/name of the bosses - it is now displayed in order Name -> Image -> Timer. I believe this is easier to consume/read and more alike to in-game Tibia.
11. Added an article to the home-page about 'Boss Timers now available' :)
12. Added a 'cookie pop-up' as required per EU regulation to warn of using cookies to keep the timer working

**Comment by PawelKusnierek** [comment]
Actually, I haven't yet merged to main - I just tried it out on 'Google Chrome' and it doesn't seem to work for me - I get 'aN:aN:aN' whenever I click a boss. Have you tested it on Chrome? 

It works fine for me on Firefox.

**Comment by assisjeferson** [comment]
I fix the policy of cookie to fix the error in google chrome

**Comment by PawelKusnierek** [comment]
I'm afraid I still get the same error even with your fix:
https://i.imgur.com/nYmMZNK.png

**Comment by assisjeferson** [comment]
Hmm, I don't know why your chrome dont save cookie.

I tested in macOS and windows10 (Version 87.0.4280.88)

https://imgur.com/DWeJrCu

**Comment by PawelKusnierek** [comment]
Ok, np, I will debug a bit later and see if I can figure it out :) I am also using 87.0.4280.88 so it's very strange. 

Btw, where did you get the boss images/gifs from?

**Comment by assisjeferson** [comment]
I get from www.tibiawiki.com.br

**Comment by PawelKusnierek** [comment]
Thanks!

**Comment by PawelKusnierek** [comment]
I pushed the code to main and it works when I access the live site, something must have been broken locally :)

Thanks again for the feature!

https://tibiapal.com/bosstimers

**Comment by PawelKusnierek** [comment]
Hey Jeferson,

I've received a few reports that some users lose the cookies/state when they turn off their computer.
The users assure me that they do not 'flush' or clear cookies, but the timer is still not saved between sessions for them.

The tool works fine for me and my friends, but I received the above report from quite a few different people so it seems unlikely to be a coincidence.

Do you have any ideas what could be causing this loss of timers between sessions for users?

Thanks,
Pawel

**Comment by assisjeferson** [comment]
Hello @PawelKusnierek 

I fixed the error, some browsers clear the cookie because max-age is missing

**Pull request merged**
