### PR TITLE
print the date target level will be reached.

### PR DESCRIPTION
**Pull request by divinity76**
screenshot: 
image

### CODE REVIEW

**Comment by divinity76** [comment]
maybe use toLocaleString() instead of toString(), i think toLocaleString try to guess which timestamp format the local user is most familiar with, and use that one..

**Comment by divinity76** [comment]
screenshot with toLocaleString: 
image
(but that is probably different depending on where in the world the user comes from)

**Comment by PawelKusnierek** [comment]
How about adding an additional input field: '(Optional) Hours of exp per day' where a user can input how long they hunt each day, and then the output can tell them when they will achieve their target level if they exp that much each day.

I think this would be more useful for most users, as not many people plan to play for 20+ hours consecutively :)

Example output:

Time needed to reach target level: 19 day(s), 19 hour(s), 9 minute(s) and 43 second(s).
At 2.5 hours of 8.5kk/h exp a day, you will reach your target level on: Wednesday, 4 July 2022, 10:19:04


(Made up numbers above, but something like that).

What do you think?

**Comment by divinity76** [comment]
@PawelKusnierek sure no problem. i ain't writing the html/css for that though, if you add the html/css for that to my branch (you have write access to the [divinity76:patch-4](https://github.com/divinity76/TibiaPal/tree/patch-4)-branch), i can probably do the rest ^^

**Comment by divinity76** [comment]
@PawelKusnierek kindof like this? https://github.com/PawelKusnierek/TibiaPal/pull/71/commits/356a37fc874566b83ec518fa61e7cc1fdad462ca

**Comment by divinity76** [comment]
@PawelKusnierek screenshot: 
image

**Comment by PawelKusnierek** [comment]
No, this is not quite what I had in mind. Both of the optional fields are to be independent.

So, for example, as a user, I input that I make 6kk/h exp per hour and in the second field, which I would call '(Optional) Hours of exp per day' I input 3, which means I hunt for 3 hours a day. This means I make 18kk exp per day (6kk * 3 hours).

Then if my starting level is Y and my target level is X, and I need 180kk exp to get from Y to X, then the tool could output that it will take me 10 days to reach my target level given my exp/h and how much I play per day (180kk / 18kk = 10).

I think this would be more useful for people to estimate how long before they reach their target level.

**Comment by PawelKusnierek** [comment]
Done in https://github.com/PawelKusnierek/TibiaPal/pull/71/commits/08570bcf0349c221238e89b3e3e87f7669ff57e6

**Comment by divinity76** [comment]
@PawelKusnierek nice, i like it ^^

**Pull request merged**
