### PR TITLE
add exp/h to exp calculator

### PR DESCRIPTION
**Pull request by divinity76**
this is a super-lazy javascript implementation, i couldn't be arsed pulling the repo down to a local nginx server and setting up a "proper" development environment, i just developed the whole thing in the javascript console on https://tibiapal.com/expcalculator 
hence the 100% pure JavaScript implementation. feel free to fix it, but it works great as-is :) 

screenshot 1:  image
screenshot 2: image

- if you are level 123, and you want level 1234, and you make 999999 exp per hour, then you need 1297 day(s), 9 hour(s), 35 minute(s) and 2 second(s)... i hope that's right

### CODE REVIEW

**Comment by PawelKusnierek** [comment]
Thanks :) I'll have a look today and move it to the .js file. Will share once it's done!

**Comment by PawelKusnierek** [comment]
I made some changes here:
https://github.com/PawelKusnierek/TibiaPal/commit/ac6d763916923f00bee9cd166ae71bb658af5f7d

And merged :)

Thanks again!

**Comment by divinity76** [comment]
@PawelKusnierek hmm there's something wrong now, if you type level and target level and press sumbit, and then write exp/h and press submit again, nothing happens 🤔

**Comment by PawelKusnierek** [comment]
@divinity76 You sure you have all the code loaded? Seems to work just fine for me

**Pull request merged**
